default = (
    "Badges",
    "Bakery",
    "Blacklist",
    "Core",
    "Drops",
    "Eval",
    "Guilds",
    "Information",
    "Leaderboards",
    "Logging",
    "LootBoxes",
    "Market",
    "StatCord",
    "Trading",
    "Tutorial",
    "Vote",
)